### ISSUE TITLE
Remove jQuery Dependency

### ISSUE THREAD

**Issue by btakita** [Foliotek/DocEditable#3]
Great project!

In the interest of making this project more embeddable, can we remove jQuery as a dependency?

**Comment by alsmpd** [comment]
Thanks for you interest int he project. 

We will be looking into removing jQuery as a dependency.

**Comment by thedustinsmith** [comment]
@alsmpd @bgrins  and I discussed it, and since Foliotek's not using DocEditable at the moment, we think this repo should deprecated in favor of https://github.com/prosemirror/prosemirror.

Thanks for the suggestion.  Hopefully prosemirror will work for you!
